## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
#將1和0切分開來
y1, y0 = y[:40], y[40:]

In [4]:
#建立隨機抽樣index for y = 1
index_1 = np.random.choice(200, 40, replace = False)
index_1

array([ 94, 135, 109, 191,  39, 181, 147, 131,  33,  76, 168, 185,  37,
       115, 182,  25,  91,  78, 137, 103,  61, 119,  45, 130,  86, 164,
        22,  26,  12,  57, 187, 174,  80, 121,  95, 171, 175, 155, 134,
        31])

In [6]:
#建立y=0之index
index_0 = []
for i, num in enumerate(np.arange(200)):
    if num not in index_1:
        index_0.append(num)
index_0 = np.array(index_0)
index_0

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  23,  24,  27,  28,  29,
        30,  32,  34,  35,  36,  38,  40,  41,  42,  43,  44,  46,  47,
        48,  49,  50,  51,  52,  53,  54,  55,  56,  58,  59,  60,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        77,  79,  81,  82,  83,  84,  85,  87,  88,  89,  90,  92,  93,
        96,  97,  98,  99, 100, 101, 102, 104, 105, 106, 107, 108, 110,
       111, 112, 113, 114, 116, 117, 118, 120, 122, 123, 124, 125, 126,
       127, 128, 129, 132, 133, 136, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 148, 149, 150, 151, 152, 153, 154, 156, 157, 158, 159,
       160, 161, 162, 163, 165, 166, 167, 169, 170, 172, 173, 176, 177,
       178, 179, 180, 183, 184, 186, 188, 189, 190, 192, 193, 194, 195,
       196, 197, 198, 199])

In [7]:
#將X, y數據依index進行分組
X1 = X[index_1]
X0 = X[index_0]

In [9]:
#以train_test_split將數據分群
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size = 10, random_state = 123)
X_train0, X_test0, y_train0, y_test0 = train_test_split(X0, y0, test_size = 10, random_state = 123)

In [10]:
#以concatenate函數將 y = 0 及 y = 1 數據串接起來
X_train = np.concatenate((X_train0, X_train1), axis = 0)
X_test = np.concatenate((X_test0, X_test1), axis = 0)
y_train = np.concatenate((y_train0, y_train1), axis = 0)
y_test = np.concatenate((y_test0, y_test1), axis = 0)

In [11]:
#檢視串接後之y_test
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])